/* File: combustionmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Fri Jul 31 11:32:58 2015
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *combustion_error;
static PyObject *combustion_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f##_,F##_)
#else
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f,F)
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = combustion_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_WRAPPEDFUNC(dtdz,DTDZ)(double*,double*,double*,double*,double*);
extern void F_WRAPPEDFUNC(temper,TEMPER)(double*,double*,double*,double*,double*,double*,double*);
extern void F_WRAPPEDFUNC(dzbdz,DZBDZ)(double*,double*,double*,double*,double*);
extern void F_WRAPPEDFUNC(dzbdz2,DZBDZ2)(double*,double*,double*,double*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************************ dTdZ ************************************/
static char doc_f2py_rout_combustion_dTdZ[] = "\
dTdZ = dTdZ(Z,gam,Zs,betha)\n\nWrapper for ``dTdZ``.\
\n\nParameters\n----------\n"
"Z : input float\n"
"gam : input float\n"
"Zs : input float\n"
"betha : input float\n"
"\nReturns\n-------\n"
"dTdZ : float";
/* extern void F_WRAPPEDFUNC(dtdz,DTDZ)(double*,double*,double*,double*,double*); */
static PyObject *f2py_rout_combustion_dTdZ(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double dTdZ = 0;
  double Z = 0;
  PyObject *Z_capi = Py_None;
  double gam = 0;
  PyObject *gam_capi = Py_None;
  double Zs = 0;
  PyObject *Zs_capi = Py_None;
  double betha = 0;
  PyObject *betha_capi = Py_None;
  static char *capi_kwlist[] = {"Z","gam","Zs","betha",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:combustion.dTdZ",\
    capi_kwlist,&Z_capi,&gam_capi,&Zs_capi,&betha_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable betha */
    f2py_success = double_from_pyobj(&betha,betha_capi,"combustion.dTdZ() 4th argument (betha) can't be converted to double");
  if (f2py_success) {
  /* Processing variable gam */
    f2py_success = double_from_pyobj(&gam,gam_capi,"combustion.dTdZ() 2nd argument (gam) can't be converted to double");
  if (f2py_success) {
  /* Processing variable Z */
    f2py_success = double_from_pyobj(&Z,Z_capi,"combustion.dTdZ() 1st argument (Z) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dTdZ */
  /* Processing variable Zs */
    f2py_success = double_from_pyobj(&Zs,Zs_capi,"combustion.dTdZ() 3rd argument (Zs) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&dTdZ,&Z,&gam,&Zs,&betha);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",dTdZ);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of Zs*/
  /* End of cleaning variable Zs */
  /* End of cleaning variable dTdZ */
  } /*if (f2py_success) of Z*/
  /* End of cleaning variable Z */
  } /*if (f2py_success) of gam*/
  /* End of cleaning variable gam */
  } /*if (f2py_success) of betha*/
  /* End of cleaning variable betha */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of dTdZ ********************************/

/*********************************** Temper ***********************************/
static char doc_f2py_rout_combustion_Temper[] = "\
Temper = Temper(H,Z,gam,Zs,betha,C)\n\nWrapper for ``Temper``.\
\n\nParameters\n----------\n"
"H : input float\n"
"Z : input float\n"
"gam : input float\n"
"Zs : input float\n"
"betha : input float\n"
"C : input float\n"
"\nReturns\n-------\n"
"Temper : float";
/* extern void F_WRAPPEDFUNC(temper,TEMPER)(double*,double*,double*,double*,double*,double*,double*); */
static PyObject *f2py_rout_combustion_Temper(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double Temper = 0;
  double H = 0;
  PyObject *H_capi = Py_None;
  double Z = 0;
  PyObject *Z_capi = Py_None;
  double gam = 0;
  PyObject *gam_capi = Py_None;
  double Zs = 0;
  PyObject *Zs_capi = Py_None;
  double betha = 0;
  PyObject *betha_capi = Py_None;
  double C = 0;
  PyObject *C_capi = Py_None;
  static char *capi_kwlist[] = {"H","Z","gam","Zs","betha","C",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO:combustion.Temper",\
    capi_kwlist,&H_capi,&Z_capi,&gam_capi,&Zs_capi,&betha_capi,&C_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable C */
    f2py_success = double_from_pyobj(&C,C_capi,"combustion.Temper() 6th argument (C) can't be converted to double");
  if (f2py_success) {
  /* Processing variable Zs */
    f2py_success = double_from_pyobj(&Zs,Zs_capi,"combustion.Temper() 4th argument (Zs) can't be converted to double");
  if (f2py_success) {
  /* Processing variable betha */
    f2py_success = double_from_pyobj(&betha,betha_capi,"combustion.Temper() 5th argument (betha) can't be converted to double");
  if (f2py_success) {
  /* Processing variable H */
    f2py_success = double_from_pyobj(&H,H_capi,"combustion.Temper() 1st argument (H) can't be converted to double");
  if (f2py_success) {
  /* Processing variable Z */
    f2py_success = double_from_pyobj(&Z,Z_capi,"combustion.Temper() 2nd argument (Z) can't be converted to double");
  if (f2py_success) {
  /* Processing variable gam */
    f2py_success = double_from_pyobj(&gam,gam_capi,"combustion.Temper() 3rd argument (gam) can't be converted to double");
  if (f2py_success) {
  /* Processing variable Temper */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&Temper,&H,&Z,&gam,&Zs,&betha,&C);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",Temper);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable Temper */
  } /*if (f2py_success) of gam*/
  /* End of cleaning variable gam */
  } /*if (f2py_success) of Z*/
  /* End of cleaning variable Z */
  } /*if (f2py_success) of H*/
  /* End of cleaning variable H */
  } /*if (f2py_success) of betha*/
  /* End of cleaning variable betha */
  } /*if (f2py_success) of Zs*/
  /* End of cleaning variable Zs */
  } /*if (f2py_success) of C*/
  /* End of cleaning variable C */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of Temper *******************************/

/*********************************** dZbdZ ***********************************/
static char doc_f2py_rout_combustion_dZbdZ[] = "\
dZbdZ = dZbdZ(Z,Zs,Zsbar,betha)\n\nWrapper for ``dZbdZ``.\
\n\nParameters\n----------\n"
"Z : input float\n"
"Zs : input float\n"
"Zsbar : input float\n"
"betha : input float\n"
"\nReturns\n-------\n"
"dZbdZ : float";
/* extern void F_WRAPPEDFUNC(dzbdz,DZBDZ)(double*,double*,double*,double*,double*); */
static PyObject *f2py_rout_combustion_dZbdZ(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double dZbdZ = 0;
  double Z = 0;
  PyObject *Z_capi = Py_None;
  double Zs = 0;
  PyObject *Zs_capi = Py_None;
  double Zsbar = 0;
  PyObject *Zsbar_capi = Py_None;
  double betha = 0;
  PyObject *betha_capi = Py_None;
  static char *capi_kwlist[] = {"Z","Zs","Zsbar","betha",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:combustion.dZbdZ",\
    capi_kwlist,&Z_capi,&Zs_capi,&Zsbar_capi,&betha_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable betha */
    f2py_success = double_from_pyobj(&betha,betha_capi,"combustion.dZbdZ() 4th argument (betha) can't be converted to double");
  if (f2py_success) {
  /* Processing variable Z */
    f2py_success = double_from_pyobj(&Z,Z_capi,"combustion.dZbdZ() 1st argument (Z) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dZbdZ */
  /* Processing variable Zsbar */
    f2py_success = double_from_pyobj(&Zsbar,Zsbar_capi,"combustion.dZbdZ() 3rd argument (Zsbar) can't be converted to double");
  if (f2py_success) {
  /* Processing variable Zs */
    f2py_success = double_from_pyobj(&Zs,Zs_capi,"combustion.dZbdZ() 2nd argument (Zs) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&dZbdZ,&Z,&Zs,&Zsbar,&betha);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",dZbdZ);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of Zs*/
  /* End of cleaning variable Zs */
  } /*if (f2py_success) of Zsbar*/
  /* End of cleaning variable Zsbar */
  /* End of cleaning variable dZbdZ */
  } /*if (f2py_success) of Z*/
  /* End of cleaning variable Z */
  } /*if (f2py_success) of betha*/
  /* End of cleaning variable betha */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of dZbdZ ********************************/

/*********************************** dZbdZ2 ***********************************/
static char doc_f2py_rout_combustion_dZbdZ2[] = "\
dZbdZ2 = dZbdZ2(Z,Zs,Zsbar,betha)\n\nWrapper for ``dZbdZ2``.\
\n\nParameters\n----------\n"
"Z : input float\n"
"Zs : input float\n"
"Zsbar : input float\n"
"betha : input float\n"
"\nReturns\n-------\n"
"dZbdZ2 : float";
/* extern void F_WRAPPEDFUNC(dzbdz2,DZBDZ2)(double*,double*,double*,double*,double*); */
static PyObject *f2py_rout_combustion_dZbdZ2(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double dZbdZ2 = 0;
  double Z = 0;
  PyObject *Z_capi = Py_None;
  double Zs = 0;
  PyObject *Zs_capi = Py_None;
  double Zsbar = 0;
  PyObject *Zsbar_capi = Py_None;
  double betha = 0;
  PyObject *betha_capi = Py_None;
  static char *capi_kwlist[] = {"Z","Zs","Zsbar","betha",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:combustion.dZbdZ2",\
    capi_kwlist,&Z_capi,&Zs_capi,&Zsbar_capi,&betha_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable betha */
    f2py_success = double_from_pyobj(&betha,betha_capi,"combustion.dZbdZ2() 4th argument (betha) can't be converted to double");
  if (f2py_success) {
  /* Processing variable Z */
    f2py_success = double_from_pyobj(&Z,Z_capi,"combustion.dZbdZ2() 1st argument (Z) can't be converted to double");
  if (f2py_success) {
  /* Processing variable Zsbar */
    f2py_success = double_from_pyobj(&Zsbar,Zsbar_capi,"combustion.dZbdZ2() 3rd argument (Zsbar) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dZbdZ2 */
  /* Processing variable Zs */
    f2py_success = double_from_pyobj(&Zs,Zs_capi,"combustion.dZbdZ2() 2nd argument (Zs) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&dZbdZ2,&Z,&Zs,&Zsbar,&betha);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",dZbdZ2);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of Zs*/
  /* End of cleaning variable Zs */
  /* End of cleaning variable dZbdZ2 */
  } /*if (f2py_success) of Zsbar*/
  /* End of cleaning variable Zsbar */
  } /*if (f2py_success) of Z*/
  /* End of cleaning variable Z */
  } /*if (f2py_success) of betha*/
  /* End of cleaning variable betha */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of dZbdZ2 *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"dTdZ",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(dtdz,DTDZ),(f2py_init_func)f2py_rout_combustion_dTdZ,doc_f2py_rout_combustion_dTdZ},
  {"Temper",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(temper,TEMPER),(f2py_init_func)f2py_rout_combustion_Temper,doc_f2py_rout_combustion_Temper},
  {"dZbdZ",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(dzbdz,DZBDZ),(f2py_init_func)f2py_rout_combustion_dZbdZ,doc_f2py_rout_combustion_dZbdZ},
  {"dZbdZ2",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(dzbdz2,DZBDZ2),(f2py_init_func)f2py_rout_combustion_dZbdZ2,doc_f2py_rout_combustion_dZbdZ2},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "combustion",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_combustion(void) {
#else
#define RETVAL
PyMODINIT_FUNC initcombustion(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = combustion_module = PyModule_Create(&moduledef);
#else
  m = combustion_module = Py_InitModule("combustion", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module combustion (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'combustion' is auto-generated with f2py (version:2).\nFunctions:\n"
"  dTdZ = dTdZ(Z,gam,Zs,betha)\n"
"  Temper = Temper(H,Z,gam,Zs,betha,C)\n"
"  dZbdZ = dZbdZ(Z,Zs,Zsbar,betha)\n"
"  dZbdZ2 = dZbdZ2(Z,Zs,Zsbar,betha)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  combustion_error = PyErr_NewException ("combustion.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));

    {
      extern double F_FUNC(dtdz,DTDZ)(void);
      PyObject* o = PyDict_GetItemString(d,"dTdZ");
      PyObject_SetAttrString(o,"_cpointer", F2PyCapsule_FromVoidPtr((void*)F_FUNC(dtdz,DTDZ),NULL));
#if PY_VERSION_HEX >= 0x03000000
      PyObject_SetAttrString(o,"__name__", PyUnicode_FromString("dTdZ"));
#else
      PyObject_SetAttrString(o,"__name__", PyString_FromString("dTdZ"));
#endif
    }
    

    {
      extern double F_FUNC(temper,TEMPER)(void);
      PyObject* o = PyDict_GetItemString(d,"Temper");
      PyObject_SetAttrString(o,"_cpointer", F2PyCapsule_FromVoidPtr((void*)F_FUNC(temper,TEMPER),NULL));
#if PY_VERSION_HEX >= 0x03000000
      PyObject_SetAttrString(o,"__name__", PyUnicode_FromString("Temper"));
#else
      PyObject_SetAttrString(o,"__name__", PyString_FromString("Temper"));
#endif
    }
    

    {
      extern double F_FUNC(dzbdz,DZBDZ)(void);
      PyObject* o = PyDict_GetItemString(d,"dZbdZ");
      PyObject_SetAttrString(o,"_cpointer", F2PyCapsule_FromVoidPtr((void*)F_FUNC(dzbdz,DZBDZ),NULL));
#if PY_VERSION_HEX >= 0x03000000
      PyObject_SetAttrString(o,"__name__", PyUnicode_FromString("dZbdZ"));
#else
      PyObject_SetAttrString(o,"__name__", PyString_FromString("dZbdZ"));
#endif
    }
    

    {
      extern double F_FUNC(dzbdz2,DZBDZ2)(void);
      PyObject* o = PyDict_GetItemString(d,"dZbdZ2");
      PyObject_SetAttrString(o,"_cpointer", F2PyCapsule_FromVoidPtr((void*)F_FUNC(dzbdz2,DZBDZ2),NULL));
#if PY_VERSION_HEX >= 0x03000000
      PyObject_SetAttrString(o,"__name__", PyUnicode_FromString("dZbdZ2"));
#else
      PyObject_SetAttrString(o,"__name__", PyString_FromString("dZbdZ2"));
#endif
    }
    
/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"combustion");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
