C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapdTdZ (dTdZf2pywrap, Z, gam, Zs, betha)
      external dTdZ
      real(kind=8) Z
      real(kind=8) gam
      real(kind=8) Zs
      real(kind=8) betha
      real(kind=8) dTdZf2pywrap, dTdZ
      dTdZf2pywrap = dTdZ(Z, gam, Zs, betha)
      end


      subroutine f2pywrapTemper (Temperf2pywrap, H, Z, gam, Zs, be
     &tha, C)
      external Temper
      real(kind=8) H
      real(kind=8) Z
      real(kind=8) gam
      real(kind=8) Zs
      real(kind=8) betha
      real(kind=8) C
      real(kind=8) Temperf2pywrap, Temper
      Temperf2pywrap = Temper(H, Z, gam, Zs, betha, C)
      end


      subroutine f2pywrapdZbdZ (dZbdZf2pywrap, Z, Zs, Zsbar, betha
     &)
      external dZbdZ
      real(kind=8) Z
      real(kind=8) Zs
      real(kind=8) Zsbar
      real(kind=8) betha
      real(kind=8) dZbdZf2pywrap, dZbdZ
      dZbdZf2pywrap = dZbdZ(Z, Zs, Zsbar, betha)
      end


      subroutine f2pywrapdZbdZ2 (dZbdZ2f2pywrap, Z, Zs, Zsbar, bet
     &ha)
      external dZbdZ2
      real(kind=8) Z
      real(kind=8) Zs
      real(kind=8) Zsbar
      real(kind=8) betha
      real(kind=8) dZbdZ2f2pywrap, dZbdZ2
      dZbdZ2f2pywrap = dZbdZ2(Z, Zs, Zsbar, betha)
      end

